.gitignore
README.md
emploi_store.py
example.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/1) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/florianjourda">florianjourda</a>

Create a emploi_store library to abstract the REST API with a nicer Python interface.

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/3) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/florianjourda">florianjourda</a>

Add first unit tests

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/4)

Handle UTF-8 properly when writing CSV file.

---

emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/6)

Add fields parameter to limit the fields returned.

---

emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/10)

Access the new LaBonneBoite API.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/11)

Document how to install emploi_store library using pip.

---

emploi_store/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/9)

Allow filters in to_csv method

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/14)

Release v0.3.

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/15)

Enable requesting LBB companies using a city ID.

---

CHANGELOG.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/16)

Release v0.3.1 with a changelog.

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/17)

Allow selecting resources by name AND version.

---

CHANGELOG.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/18)

Release new version.

---

CHANGELOG.md
emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/19)

Add support for the LBF API.

---

CHANGELOG.md
emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/21)

Added a method num_records to count the number of records in a resource without listing them all.

---

CHANGELOG.md
emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/22)

Update the to_csv method of resources to modify or count records on the fly.

---

CHANGELOG.md
emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/23)

Fix the to_csv method so that the iterator callback can use the total number of records.

---

CHANGELOG.md
emploi_store/__init__.py
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/24)

Add support for the early events API.

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/27)

[API] Add a new the matchviaSoftSkills API.

---

CHANGELOG.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/28)

Bump the version to 0.8.0

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29)

[Better Error] Improve error raised when authentication fails.

---

README.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/30)

Add documentation on how to setup the dev environment.

---

.circleci/config.yml
README.md
setup.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/31)

Use requests-mock package for testing.

---

CHANGELOG.md
README.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/33)

Document the release process and bump version to 0.8.1.

---

.circleci/config.yml
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/36)

[Better CI] Add code coverage and push to codecov.io

---

.circleci/config.yml
.pylintrc
emploi_store/__init__.py
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/38)

Run pylint on CI and use six to handle unicode on Python 2 and 3.

---

emploi_store/__init__.py
tests/emploi_store_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/37)

Add support for physical events ressource

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/39)

Update subscription procedure in the ReadMe

---

CHANGELOG.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/41)

Ship the type stubs with the PyPi package.

---

emploi_store/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/45)

Fix new pylint issue

---

.circleci/config.yml
emploi_store/__init__.pyi

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/43)

Check type stubs in the CI.

---

emploi_store/__init__.py
emploi_store/__init__.pyi
tests/emploi_store_test.py

Fix #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/46)

Accept a single string for rome_codes and naf_codes args.

---

.circleci/config.yml
README.md
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/python-emploi-store/47)

Deploy tags to PyPi in CI pipeline
